version: '3.7'

volumes:
  logs:
    driver: local
  mysql_data:

services:
  api:
    image: 'canals/php:latest'
    working_dir: /var/www
    command: php -S 0.0.0.0:80 -t public
    environment:
      docker: "true"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: minipress
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: minipress_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "4500:8080"
